version: "3"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8082"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http.tls=true"
      # ACME
      # - "--certificatesresolvers.primary.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.primary.acme.storage=acme.json"
      # - "--certificatesresolvers.primary.acme.httpchallenge.entrypoint=web"
    ports:
      - 80:80
      - 443:443
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN_NAME_TRAEFIK}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=trauth"
      - "traefik.http.routers.api.entrypoints=web-secure"
      # - "traefik.http.routers.api.tls.certresolver=primary"
      - "traefik.http.middlewares.trauth.forwardauth.address=http://trauth:8080/"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./acme.json:/acme.json"

  sconwarbackend:
    image: sconwar-api:local
    container_name: sconwarbackend
    restart: unless-stopped
    environment:
      - API_TOKEN=${PRIVILEGED_API_TOKEN}
      - BASE_HOST=${DOMAIN_NAME_API}
    volumes: 
      - "./sconwar.db:/db.sqlite"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sconwarbackend.rule=Host(`${DOMAIN_NAME_API}`)"
      # - "traefik.http.routers.sconwarbackend.middlewares=trauth"
      - "traefik.http.routers.sconwarbackend.entrypoints=web-secure"
      # - "traefik.http.routers.sconwarbackend.tls.certresolver=primary"

  sconwarfrontend:
    image: sconwar-ui:local
    container_name: sconwarfrontend
    restart: unless-stopped
    volumes:
      - "${PWD}/.env:/usr/src/app/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sconwarfrontend.rule=Host(`${DOMAIN_NAME_UI}`)"
      # - "traefik.http.routers.sconwarfrontend.middlewares=trauth"
      - "traefik.http.routers.sconwarfrontend.entrypoints=web-secure"
      # - "traefik.http.routers.sconwarfrontend.tls.certresolver=primary"

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - prom-storage:/etc/prometheus/
      - prom-storage:/prometheus
      - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prom.rule=Host(`${DOMAIN_NAME_PROMETHEUS}`)"
      - "traefik.http.routers.prom.middlewares=trauth"
      - "traefik.http.routers.prom.entrypoints=web-secure"
      # - "traefik.http.routers.prom.tls.certresolver=primary"
    links:
      - cadvisor:cadvisor
      - sconwarbackend:sconwarbackend
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN="${DOMAIN_NAME}"
      - GF_SMTP_ENABLED=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${DOMAIN_NAME_GRAFANA}`)"
      - "traefik.http.routers.grafana.middlewares=trauth"
      - "traefik.http.routers.grafana.entrypoints=web-secure"
      # - "traefik.http.routers.grafana.tls.certresolver=primary"

  trauth:
    image: leonjza/trauth
    container_name: trauth
    environment:
      - TRAUTH_DOMAIN=${DOMAIN_NAME}
      - TRAUTH_PASSWORD_FILE_LOCATION=/config/htpass
    volumes:
      - ./htpass:/config/htpass
    restart: unless-stopped

volumes:
    grafana-storage:
    prom-storage:
