{
 "title": "Sonwar Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Damage taken",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sconwar_damage_taken_total" }
   ]
  },
  {
   "title": "Total Score Awarded",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sconwar_score_awarded_total" }
   ]
  },
  {
   "title": "Total Creeps Killed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sconwar_creeps_killed_total" }
   ]
  },
  {
   "title": "Total Players Killed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sconwar_players_killed_total" }
   ]
  },
  {
   "title": "Total Actions Queued ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sconwar_player_actions_queued_total"
    }
   ]
  },
  {
   "title": "Total HTTP Actions Executed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sconwar_player_api_actions_total"
    }
   ]
  },
  {
   "title": "Powerup Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sconwar_powerups_collected_total"
    },
    { "expr": "sconwar_powerups_used_total" }
   ]
  },
  {
   "title": "Game Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sconwar_creep_damage_taken_total[1m])",
     "legendFormat": "Creep Damage Taken"
    },
    {
     "expr": "rate(sconwar_creep_distance_moved_total[1m])  ",
     "legendFormat": "Creep Distance Moved"
    },
    {
     "expr": "rate(sconwar_creeps_killed_total[1m])  ",
     "legendFormat": "Creeps Killed"
    },
    {
     "expr": "rate(sconwar_players_killed_total[1m])  ",
     "legendFormat": "Players Killed"
    },
    {
     "expr": "rate(sconwar_attack_executed_total[1m])  ",
     "legendFormat": "Attacks Executed"
    },
    {
     "expr": "rate(sconwar_player_created_total[1m])  ",
     "legendFormat": "Players Created"
    },
    {
     "expr": "rate(sconwar_player_actions_queued_total[1m])  ",
     "legendFormat": "Actions Queued"
    },
    {
     "expr": "rate(sconwar_damage_taken_total[1m])  ",
     "legendFormat": "Damaged taken by {{ entity }}"
    },
    {
     "expr": "rate(sconwar_powerups_collected_total[1m])  ",
     "legendFormat": "Power ups collected"
    },
    {
     "expr": "rate(sconwar_powerups_used_total[1m])  ",
     "legendFormat": "Power ups used"
    }
   ]
  }
 ]
}